language: go
matrix:
  include:
  - go: 1.4.3
  - go: 1.5.4
  - go: 1.6.3
  - go: 1.7
  - go: tip
  allow_failures:
  - go: tip
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- echo "Test and track coverage" ; $HOME/gopath/bin/goveralls -service=travis-ci
- echo "Build examples" ; cd examples && go build
- echo "Check if gofmt'd" ; diff -u <(echo -n) <(gofmt -d -s .)
